// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinoPDV.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NinoPDV.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518013849_AddProductsComplexSchema")]
    partial class AddProductsComplexSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NinoPDV.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("text");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cellphone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Complement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FoundationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("MunicipalRegistration")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("PurchaseLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferencePoint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Shareholder")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slogan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StateRegistration")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.EmailSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Encryption")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Recipient")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Server")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ModifierGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("integer");

                    b.Property<int>("MinSelections")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceRule")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ModifierGroups");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ModifierOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModifierGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModifierGroupId");

                    b.HasIndex("ProductId");

                    b.ToTable("ModifierOptions");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.PrintSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<bool>("Print3DGraphs")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintAccountDivision")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintAccountOnCloseOrders")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintAccountReceipt")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintAddress")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintAllWaiters")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintCanceledOrdersOnClosure")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintCancellationSummary")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintCashierAttendant")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintCashierClosure")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintClientInServices")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintCnpj")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintCodeInServices")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintComandaPassword")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintComandaRemainingBalanceInServices")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintCompanyLogo")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintDeliveryAddressInAdvance")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintDeliveryCouponSecondCopy")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintDetailedServices")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintFinancialOperations")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintGroupedPackages")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintHighlightedAddress")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintHighlightedLocal")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintLocalInServices")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintObservationsOnOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintOrderObservationInServices")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintPanelPassword")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintPaymentGuide")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintPermanence")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintPhone1")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintPhone2")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintPrepCancellation")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintProductDetails")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintProductionConference")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintProductsOnClosure")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintSeparateLocalAndAttendant")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintServiceSeparatorLine")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintServicesInLargeFont")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintServicesWithoutAsking")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintSlogan")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintWaitersInReport")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowPrintQuestion")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("PrintSettings");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFractionable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ProductCombo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FixedPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParentComboId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProductId");

                    b.HasIndex("ParentComboId");

                    b.ToTable("ProductCombos");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ProductComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParentProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientProductId");

                    b.HasIndex("ParentProductId");

                    b.ToTable("ProductCompositions");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AbrirComandaSemSolicitarCliente")
                        .HasColumnType("boolean");

                    b.Property<bool>("AceitarPedidosDeliveryAutomaticamente")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoLogout")
                        .HasColumnType("boolean");

                    b.Property<int>("AutoLogoutTime")
                        .HasColumnType("integer");

                    b.Property<bool>("ComandaPrePaga")
                        .HasColumnType("boolean");

                    b.Property<bool>("ComissaoNaVendaBalcao")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ConfirmarAoLancandoQuantidadesElevadas")
                        .HasColumnType("boolean");

                    b.Property<bool>("ControlarLoteDoEstoque")
                        .HasColumnType("boolean");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("DesativarAvisosDeEstoqueAbaixoDoMinimo")
                        .HasColumnType("boolean");

                    b.Property<string>("DropboxToken")
                        .HasColumnType("text");

                    b.Property<bool>("ExibirTelaVendaRapidaEmTelaCheia")
                        .HasColumnType("boolean");

                    b.Property<bool>("FazerLogoutAposLancadoPedidoDoDesktop")
                        .HasColumnType("boolean");

                    b.Property<bool>("FazerLogoutNoTabletAposLancadoPedido")
                        .HasColumnType("boolean");

                    b.Property<bool>("FilaDePesagemNasComandas")
                        .HasColumnType("boolean");

                    b.Property<bool>("HabilitarEventosParaCatraca")
                        .HasColumnType("boolean");

                    b.Property<bool>("HabilitarIdentificadorDeChamadas")
                        .HasColumnType("boolean");

                    b.Property<bool>("HabilitarUsoDeBalanca")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<bool>("LembrarUltimoAtendenteNasVendas")
                        .HasColumnType("boolean");

                    b.Property<bool>("MostrarCamposFiscaisETributarios")
                        .HasColumnType("boolean");

                    b.Property<bool>("MostrarProdutosCanceladosNasVendas")
                        .HasColumnType("boolean");

                    b.Property<bool>("ObrigarInformarMotivoDeCancelamentos")
                        .HasColumnType("boolean");

                    b.Property<bool>("ObservacaoComoNomeDeComanda")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirEstoqueNegativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("PesarProdutoAoSelecionarComanda")
                        .HasColumnType("boolean");

                    b.Property<bool>("RealizarBackupAutomaticamente")
                        .HasColumnType("boolean");

                    b.Property<bool>("RedirecionarParaAMesaPrincipal")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReservarMesasAoJuntar")
                        .HasColumnType("boolean");

                    b.Property<string>("TefType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoDispositivoIdentificador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloudAccountId")
                        .HasColumnType("text");

                    b.Property<string>("CloudUserToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("EmailVerificationCodeExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OAuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.Category", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.EmailSetting", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Company", "Company")
                        .WithOne("EmailSetting")
                        .HasForeignKey("NinoPDV.Api.Models.EmailSetting", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ModifierGroup", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Product", "Product")
                        .WithMany("ModifierGroups")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ModifierOption", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.ModifierGroup", "ModifierGroup")
                        .WithMany("Options")
                        .HasForeignKey("ModifierGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinoPDV.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModifierGroup");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.PrintSetting", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Company", "Company")
                        .WithOne("PrintSetting")
                        .HasForeignKey("NinoPDV.Api.Models.PrintSetting", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.Product", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ProductCombo", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Product", "ChildProduct")
                        .WithMany()
                        .HasForeignKey("ChildProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NinoPDV.Api.Models.Product", "ParentCombo")
                        .WithMany("ComboItems")
                        .HasForeignKey("ParentComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProduct");

                    b.Navigation("ParentCombo");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ProductComposition", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Product", "IngredientProduct")
                        .WithMany()
                        .HasForeignKey("IngredientProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NinoPDV.Api.Models.Product", "ParentProduct")
                        .WithMany("Ingredients")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientProduct");

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ProductPrice", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.SaleItem", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinoPDV.Api.Models.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.SystemSetting", b =>
                {
                    b.HasOne("NinoPDV.Api.Models.Company", "Company")
                        .WithOne("SystemSetting")
                        .HasForeignKey("NinoPDV.Api.Models.SystemSetting", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.Company", b =>
                {
                    b.Navigation("EmailSetting");

                    b.Navigation("PrintSetting");

                    b.Navigation("SystemSetting");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.ModifierGroup", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.Product", b =>
                {
                    b.Navigation("ComboItems");

                    b.Navigation("Ingredients");

                    b.Navigation("ModifierGroups");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("NinoPDV.Api.Models.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
